[theme] # You have to add this line

primaryColor = '#FF8C02' # Bright Orange

backgroundColor = '#00325B' # Dark Blue

secondaryBackgroundColor = '#00325B' # Lighter Blue

textColor = '#FF8C02'

font = "sans serif"
